"use client";

import { Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { CheckCircle2, Download, LayoutDashboard, Receipt } from "lucide-react";

function PaymentSuccessContent() {
  const params = useSearchParams();
  const plan = params.get("plan") ?? "Future Pro";
  const payment = params.get("payment") ?? "pay_demo";

  return (
    <main className="grid min-h-screen place-items-center bg-ink bg-radial-grid px-4 text-saffron-900">
      <div className="glass w-full max-w-2xl rounded-2xl p-8 text-center">
        <CheckCircle2 className="mx-auto h-16 w-16 text-saffron-600" />
        <p className="mt-5 text-sm uppercase tracking-[0.22em] text-saffron-700">Payment success</p>
        <h1 className="mt-3 text-4xl font-semibold">Enrollment activated</h1>
        <p className="mt-4 text-saffron-900/62">
          {plan} is unlocked. A confirmation email and receipt are generated by the payment verification API.
        </p>
        <div className="mt-6 rounded-xl border border-white/10 bg-white/[0.05] p-5 text-left">
          <p className="flex items-center gap-2 font-semibold"><Receipt className="h-4 w-4 text-saffron-600" /> Invoice</p>
          <p className="mt-3 text-sm text-saffron-900/58">Plan: {plan}</p>
          <p className="mt-1 text-sm text-saffron-900/58">Payment ID: {payment}</p>
          <p className="mt-1 text-sm text-saffron-900/58">Status: Paid</p>
        </div>
        <div className="mt-6 grid gap-3 sm:grid-cols-2">
          <button onClick={() => window.print()} className="inline-flex h-12 items-center justify-center gap-2 rounded-lg border border-white/12 bg-white/8 font-semibold hover:bg-white/12">
            <Download className="h-4 w-4" /> Invoice
          </button>
          <a href="/dashboard" className="inline-flex h-12 items-center justify-center gap-2 rounded-lg bg-saffron-500 font-semibold shadow-glow">
            <LayoutDashboard className="h-4 w-4" /> Dashboard
          </a>
        </div>
      </div>
    </main>
  );
}

export default function PaymentSuccessPage() {
  return (
    <Suspense fallback={<main className="min-h-screen bg-ink" />}>
      <PaymentSuccessContent />
    </Suspense>
  );
}


